version: 2.1
jobs:
  build:
    working_directory: ~/node-circle-ci
    docker:
      - image: cimg/node:16.10.0 # the primary container, where your job's commands are run

    steps:
      - checkout
      - run: 
          name : install-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Deploy
          command:  curl -X POST -d {} https://api.netlify.com/build_hooks/61dd369a65155abbf2eb951e
